version: '2'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.3
    env_file: .master.env
    ports:
      - '8080:8080'
    networks:
      spark-net:
        ipv4_address: 10.28.5.150
    volumes:
      - spark-content:/opt/bitnami/spark/
    restart: always

  spark-worker:
    depends_on:
      - spark-master
    image: docker.io/bitnami/spark:3.3
    env_file: .worker.env
    networks:
      - spark-net
    restart: always

networks:
  spark-net:
    external:
      name: spark-net

volumes:
  spark-content:
    external: true
    # networks:
    #   spark-net:
    #     ipam:
    #       driver: default
    #       config:
    #         - subnet: 192.168.214.0/24
