project               = "qwiklabs-gcp-01-773ec8c75c09"
region                = "us-central1"
zone                  = "us-central1-a"
notebook_path         = "/home/std-logic/__0xDataDev/bigspark-challenge-spark/gcp/bigspark-zeppelin-notebooks/"
zeppelin_bucket       = "zeppelin-notebooks-bucket"
location              = "US"
cluster_name          = "bigspark-zeppelin-cluster"
machine_type          = "n1-standard-2"
aws_access_key_id     = ""
aws_secret_access_key = ""

