version: '2'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.3
    env_file: .master.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - '8080:8080'
    networks:
      - spark-net
    volumes:
      - spark-data:/opt/bitnami/spark/
    restart: always

  spark-worker:
    depends_on:
      - spark-master
    image: docker.io/bitnami/spark:3.3
    env_file:
      - .worker.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - spark-net
    volumes:
      - tpcds-data:/usr/local/tpcds_data

    restart: always

  zeppelin:
    image: apache/zeppelin:0.10.1
    ports:
      - 9098:8080
    volumes:
      - zeppelin-logs:/logs
      - zeppelin-notebook:/notebook
      - spark-data:/opt/spark
      - tpcds-data:/usr/local/tpcds_data
    env_file:
      - .zeppelin.env
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - spark-net
    restart: always

networks:
  spark-net:
    external:
      name: spark-net

volumes:
  spark-data:
  zeppelin-logs:
    external: true
  zeppelin-notebook:
    external: true
  tpcds-data:
    external: true
